# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.19.3
kotlin_loader_version=1.13.12+kotlin.2.4.0
modmenu_version=18.0.0-beta.1
# Mod Properties
mod_version=1.0
maven_group=io.hwfg
archives_base_name=kriscraft
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.145.1+26.1
